//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorApp.Content
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContractorEntities1 : DbContext
    {
        public ContractorEntities1()
            : base("name=ContractorEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contractor> Contractors { get; set; }
        public virtual DbSet<Employer> Employers { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Supervisor> Supervisors { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
    }
}
