//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorApp.Content
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Supervisor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supervisor()
        {
            this.Contractors = new HashSet<Contractor>();
        }
    
        public int SupervisorID { get; set; }
        [DisplayName("Last Name")]
        public string SupLName { get; set; }
        [DisplayName("First Name")]
        public string SupFName { get; set; }
        [DisplayName("Supervisor's Full Name")]
        public String FullName
        {
            get { return SupFName + " " + SupLName; }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contractor> Contractors { get; set; }
    }
}
